import pandas as pd
df = pd.read_csv(r"F:\mlproject\New folder\dataset\insurance.csv")
print("\nFirst 5 rows:")
print(df.head())
print("\nLast 5 rows:")
print(df.tail())
print("\nDataset shape:")
print(df.shape)
print("\nData types:")
print(df.dtypes)
print("\nDataset information:")
df.info()
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:")
print(df.duplicated().sum())
print("\nSex values:")
print(df["sex"].value_counts())

print("\nSmoker values:")
print(df["smoker"].value_counts())

print("\nRegion values:")
print(df["region"].value_counts())
print("\nRandom sample:")
print(df.sample(5))
print("\nEDA completed successfully!")